api_platform:
    title: Hello API Platform
    version: 1.0.0
    use_symfony_listeners: true
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    enable_swagger_ui: true
    enable_docs: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header